version: '3.8'

services:
  web:
    container_name: django
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: postgres 
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER : "postgres"
      POSTGRES_PASSWORD: "postgres"