# Generated by Django 4.0.6 on 2023-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_ads_building_payment_ads_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment_ads',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
