# Generated by Django 4.0.6 on 2023-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_ads_title_alter_payment_ads_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='Title',
            field=models.CharField(default='sds', max_length=50),
        ),
    ]
