# Generated by Django 4.0.6 on 2023-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='profile_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='online',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
