# Generated by Django 4.0.6 on 2023-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_online_profile_id_alter_online_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='profile_id',
            field=models.IntegerField(),
        ),
    ]
