# Generated by Django 4.0.6 on 2023-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_online_building_id_alter_online_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='building_id',
            field=models.IntegerField(),
        ),
    ]
