# Generated by Django 4.0.6 on 2023-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_online_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='test test test', max_length=100),
        ),
    ]
