# Generated by Django 4.0.6 on 2023-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_ads_building_id_payment_ads_building_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
    ]
