# Generated by Django 4.0.6 on 2023-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_vote_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='vote_active',
            field=models.BooleanField(default=False),
        ),
    ]
