# Generated by Django 4.0.6 on 2023-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_vote_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='profile_id',
        ),
        migrations.AlterField(
            model_name='pool',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
