# Generated by Django 4.0.6 on 2023-03-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_pool_profile_id_alter_pool_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_payment',
            field=models.BooleanField(default=False),
        ),
    ]
