# Generated by Django 4.0.6 on 2023-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_profile_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='payment_date',
            field=models.DateField(default='2010-10-10'),
        ),
    ]
