# Generated by Django 4.0.6 on 2023-04-02 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_building_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='answered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
