# Generated by Django 4.0.6 on 2023-04-02 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_pool_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='answered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pool',
            name='answered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
