# Generated by Django 4.2 on 2023-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_vote_answered_alter_pool_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/./profile_pics.png', upload_to=''),
        ),
    ]
